[font]
normal = { family = "MesloLGM Nerd Font Mono", style = "Regular" }
size = 15

[keyboard]

[[keyboard.bindings]]
chars = "\u0002\""
key = "E"
mods = "Command" # split tmux window vertically

[[keyboard.bindings]]
chars = "\u0002%"
key = "E"
mods = "Command|Shift" # split tmux window horizontally

[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Command" # create a new tmux window

[[keyboard.bindings]]
chars = "\u0002x"
key = "W"
mods = "Command" # kill the current pane

[[keyboard.bindings]]
chars = "\u0002&"
key = "W"
mods = "Command|Shift" # kill the current window

[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Command" # select tmux window 1

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Command" #                ... 2

[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Command" #                ... 3

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Command" #                ... 4

[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Command" #                ... 5

[[keyboard.bindings]]
chars = "\u00026"
key = "Key6"
mods = "Command" #                ... 6

[[keyboard.bindings]]
chars = "\u00027"
key = "Key7"
mods = "Command" #                ... 7

[[keyboard.bindings]]
chars = "\u00028"
key = "Key8"
mods = "Command" #                ... 8

[[keyboard.bindings]]
chars = "\u00029"
key = "Key9"
mods = "Command" #                ... 9

[[keyboard.bindings]]
chars = "\u0002\u001b[D"
key = "Left"
mods = "Command" # switch to tmux pane on the left

[[keyboard.bindings]]
chars = "\u0002\u001b[C"
key = "Right"
mods = "Command" # switch to tmux pane on the right

[[keyboard.bindings]]
chars = "\u0002\u001b[B"
key = "Down"
mods = "Command" # switch to tmux pane on the bottom

[[keyboard.bindings]]
chars = "\u0002\u001b[A"
key = "Up"
mods = "Command" # switch to tmux pane on the top

[[keyboard.bindings]]
chars = "\u001b\r"
key = "Return"
mods = "Alt" # send ESC+CR (meta-enter) for option+enter newline

[[keyboard.bindings]]
chars = "\u001bb"
key = "Left"
mods = "Alt" # readline backward-word for option+left

[[keyboard.bindings]]
chars = "\u001bf"
key = "Right"
mods = "Alt" # readline forward-word for option+right

[hints]

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
persist = false
mouse = { enabled = true, mods = "Command" }
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https?://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

